### PR TITLE
Settings for Delphi 7

### PR DESCRIPTION
**Pull request by ricardojr01**
Added some directives with delphi 7 functions.

### CODE REVIEW

**Comment by alexmerkel** [comment]
Hi Ricardo,

thank you very much for your pull requests.
On first glance it looks good but as I said in your issue #1, I'm unable to perform any tests myself at the moment. Were you able to test the patched source with a newer version of Delphi (e.g. Delphi 10.X) to make sure there are no regressions? 

Cheers,
Alex

**Comment by ricardojr01** [comment]
Hi Alex

I am happy to contribute. Unfortunately I don't have access to other versions of delphi. My tests were done only on delphi 7.

Cheers,
Ricardo

**Comment by alexmerkel** [comment]
Hi Ricardo,

sorry for the delay, it took me a while to arrange a modern(ish) version of Delphi to test the changes against.
Unfortunately, my compiler (10.1) throws an error because it does not understand the conditional compilation `{$IFDEF DELPHI_7}`.
I see you are including a new file `Directives.inc` everywhere, but the file is missing from the pull request. Maybe  `DELPHI_7` is defined in there?

**Comment by ricardojr01** [comment]
Hi Alex,

I'm sorry for the delay, my 9 month old son is using all my free time. I got a version of delphi 10.1 Seatle and I understood my mistake, the DELPHI_7 directive is equivalent to versions greater or equal. To avoid problems I made the correction for Delphi 7 version specifically. This time I compiled in versions 7 and 10.1 Seatle and I had no problems.

**Comment by alexmerkel** [comment]
Hi Ricardo,

thanks for the updated commit. I verified that it compiles using 10.1, so I'm happy to merge.
Thank you very much for your pull request.
Cheers!

**Pull request merged**
